Repository TFDefect/TFDefectGA, pull requests merged in 2025-02, with the labels that each got.

#1 Ajout des issue templates, politique de branche et pull request templ…
  .github/ISSUE_TEMPLATE/demande-de-fonctionnalité.md
  .github/ISSUE_TEMPLATE/rapport-de-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/branches.md
Labels: documentation

#2 Doc/ajout template kanban
  .github/ISSUE_TEMPLATE/documentation.md
  .github/test.md
Labels: documentation

#13 Implémentation de l'adaptateur Git
  core/parsers/terraform_parser.py
  infrastructure/adapters/external_tools/__init__.py
  infrastructure/adapters/git/__init__.py
  infrastructure/adapters/git/git_adapter.py
  infrastructure/adapters/git/git_changes.py
  infrastructure/adapters/ml/__init__.py
  requirements.txt
  utils/logger_utils.py
Labels: feature, enhancement

#15 Extraction des métriques terraform
  .github/PULL_REQUEST_TEMPLATE.md
  app/action_runner.py
  config/config.py
  core/use_cases/analyze_tf_code.py
  core/use_cases/detect_tf_changes.py
  data/main.tf
  infrastructure/adapters/external_tools/terra_metrics.py
Labels: feature, enhancement

#20 Ajout d'un model ML naif
  app/action_runner.py
  core/parsers/metrics_extractor.py
  core/use_cases/analyze_tf_code.py
  infrastructure/adapters/external_tools/terra_metrics.py
  infrastructure/adapters/git/git_adapter.py
  infrastructure/adapters/git/git_changes.py
  infrastructure/adapters/ml/base_model.py
  infrastructure/adapters/ml/dummy_model.py
  requirements.txt
  utils/logger_utils.py
Labels: feature

#21 Ajout du template de documentation
  .github/ISSUE_TEMPLATE/documentation.md
Labels: documentation
